services:
  amplify:
    build:
      context: .
    user: node
    tty: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:/home/node/workspace:cached
      - ~/.aws/:/home/node/.aws
    working_dir: /home/node/workspace